# Generated by Django 5.0 on 2025-07-03 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('script_file', models.FileField(upload_to='scripts/')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('total_words', models.IntegerField(default=0)),
                ('correct_words', models.IntegerField(default=0)),
                ('missing_words', models.IntegerField(default=0)),
                ('wrong_words', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcribed_text', models.TextField()),
                ('script_text', models.TextField()),
                ('processing_time', models.FloatField(default=0.0)),
                ('whisper_model_used', models.CharField(default='base', max_length=50)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_result', to='audio_checker.audioanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='WordComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_word', models.CharField(max_length=100)),
                ('audio_word', models.CharField(max_length=100)),
                ('word_index', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('error_type', models.CharField(choices=[('correct', 'Correct'), ('missing', 'Missing'), ('wrong', 'Wrong'), ('extra', 'Extra')], default='correct', max_length=20)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_comparisons', to='audio_checker.audioanalysis')),
            ],
            options={
                'ordering': ['word_index'],
            },
        ),
    ]
