# Generated by Django 5.0 on 2025-07-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='segments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='whisper_model_used',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
